const projects = [
    {
        id:"1",
        author:"kms",
        picture:"https://cn-web-site.s3.amazonaws.com/Hot+Topics+2022/Ukraine+HT-new.png",
        name:"Ukraine Relief & Recovery",
        title:"",
        type:"hot",
        topic:"",
        content:"Since the war began between Ukraine and the Russian Federation on February 24, 2022*, according to a report released in June by the United Nations High Commissioner for Refugees (UNHCR), over 7 million people have been displaced – almost 5 million of which have been recorded across Europe. What has been reported as the largest refugee crisis since World War II has become a far-reaching humanitarian disaster threatening economies across Europe. This crisis includes rising inflation and shortages of food and other goods. Donor support is still needed for relief and recovery efforts, but that need will eventually shift to the long-term rebuilding of Ukraine's economy and infrastructure. On this page is a list of highly-rated charities providing humanitarian services in Ukraine and the surrounding region. To the extent that we can also highlight nonprofits addressing peace-building efforts to encourage diplomacy and prevent further military action, they will be included. We encourage you to re-share and visit this page often.The 3- and 4-Star rated charities included in this list have earned their ratings by being financially efficient and transparent in their operations. These nonprofits are larger and national in scope. Please click on the names of the high-performing charities included in our list to learn more about their mission, programs, and services and to make a donation via the Giving Basket.",
        day:"",
        update:"",
        member:[],
        activities:[]
    },
    {
        id:"2",
        author:"kms",
        picture:"https://cn-web-site.s3.amazonaws.com/Hot+Topics+2022/afghanistan_earthquake_htweb.png",
        name:"Afghanistan Earthquake",
        title:"",
        type:"hot",
        topic:"",
        content:"On Wednesday, June 22, a 5.9 magnitude earthquake struck southeast Afghanistan near the Pakistani border. Initial reports estimate more than 1,000 people may have died and over 2,000 homes destroyed. The area impacted is remote; far from hospitals and aid, and already overwhelmed with a food crisis. Clean water, food, medical supplies, as well as shelter from severe weather, are all in short supply.The highly rated organizations included on this page have been vetted by Charity Navigator analysts as providing relief and support to those affected with dedicated funds in response. Charity Navigator will continue to update this resource as other nonprofits providing or funding direct relief are approved. Please click on the names of the high-performing charities included in our list to learn more about their mission, programs, and services and to make a donation via the Giving Basket.",
        day:"",
        update:"",
        member:[],
        activities:[]
    },
    {
        id:"3",
        author:"kms",
        picture:"https://cn-web-site.s3.amazonaws.com/Hot+Topics+2022/roe_v_wade_web.png",
        name:"Roe v. Wade Reversal",
        title:"",
        type:"hot",
        topic:"",
        content:"On June 24, 2022, the U.S. Supreme Court officially reversed Roe v. Wade. As access to abortion is now decided at a state level, and support and alternatives vary, many people are looking for ways to support women, children, and families affected by this monumental change.Understanding this is a deeply personal issue for many, we are taking a holistic approach to our recommendations, providing multiple perspectives and strategies to support women’s reproductive health and unintended pregnancies. Our analysts have identified highly rated (3- and 4-star) charities addressing a variety of subjects ranging from abortion access, women’s health, adoption support, and infant and young child care. Learn more about each organization by clicking its name and consider supporting organizations that align with your values by donating via the Charity Navigator Giving Basket.",
        day:"",
        update:"",
        member:[],
        activities:[]
    },
    {
        id:"4",
        author:"kms",
        picture:"https://media-cldnry.s-nbcnews.com/image/upload/newscms/2020_53/3438733/201230-black-table-arts-al-1129.jpg",
        name:"Black-Founded Nonprofits",
        title:"",
        type:"hot",
        topic:"",
        content:"As Americans focus on finding solutions for long-standing racial disparities, many have been moved to support businesses that are Black-owned.",
        day:"",
        update:"",
        member:[],
        activities:[]
    },
    {
        id:"5",
        author:"kms",
        picture:"https://cn-web-site.s3.amazonaws.com/Hot+Topics+2022/refugee_web.png",
        name:"Immigration and Refugees",
        title:"",
        type:"popular",
        topic:"",
        content:"Built and shaped by immigrants and refugees alike, the United States is a nation to admire. Experiences and cultures, memories passed down by our ancestors meld to become our collective consciousness. Wherever tragedy strikes individuals and families rally to speak on behalf of the voiceless, telling stories that deserve to be told, taking action to relieve the pain.There are highly-rated organizations that provide services and resources to individuals and families seeking a better outcome in the United States than what they experienced in their home countries. Fortunately, there are organizations advocating for and supporting these communities. Groups that help immigrants build and settle into a different life, ultimately one that many hope will be better.Current events highlight the need for a larger conversation about families fleeing their homes, communities, and countries in the wake of famine, social unrest, persecution, war, and environmental disasters. Highly-rated charities advocate for and provide relief to refugees, internally displaced persons, and stateless groups around the world. They seek to provide for individuals basic needs like food, water, and shelter while advocating for policies and legislation that will address the root causes of this crisis.The highly-rated charities included in this list are leading the conversations on immigration, refugees, and global migration. And, their 3- and 4-star ratings speak to their commitment to upholding the highest standards for financial health and accountability and transparency. Take action on the issues that are important to you, do your part to help those less fortunate, give confidently to one of these outstanding organizations today.",
        day:"",
        update:"",
        member:[],
        activities:[]
    },
    {
        id:"6",
        author:"kms",
        picture:"https://cn-web-site.s3.amazonaws.com/hot-topics/rsz_1madison-lavern-4gcqrf3-f2i-unsplash.jpg",
        name:"Mental Health Awareness",
        title:"",
        type:"",
        topic:"",
        content:"The importance of the promotion of good mental health has been heightened in recent years as we are faced with increased stressors of daily life, Annually, in May, Mental Health Month provides a dedicated time to raise awareness about the realities of individuals living with mental illness, including anxiety disorders, and ways to manage and achieve mental wellness. For many, mental illness is a term loaded with negative connotations, misconceptions, and stigma, which is what makes events like Mental Health Month so important. All month long, mental health care providers across the country will be sponsoring events to engage their communities in education and awareness building to better support individuals who are struggling with mental illness on their path to mental wellness. We hope you will consider supporting one of these highly-rated 3- and 4-star rated organizations as they support and advocate for those struggling with mental illness and mental health disorders. ",
        day:"",
        update:"",
        member:[],
        activities:[]
    },
    {
        id:"7",
        author:"",
        picture:"https://cn-web-site.s3.amazonaws.com/Hot+Topics+2022/stop-gun-violence.png",
        name:"Racial Justice & Civil Rights",
        title:"",
        type:"",
        topic:"",
        content:"Following the murder of George Floyd, much of the nation's attention focused on racial injustice and the deep-rooted issues that allow inequality to continue. The pursuit of racial justice and equity continues with a goal of bringing about systemic change so that future generations can live in a world without prejudice. In an effort to provide those passionate about racial justice with resources, Charity Navigator presents this list of highly-rated nonprofits whose missions are focused on defending civil rights, protecting legal rights, and/or promoting tolerance and understanding among different races, ethnicities, genders, religions, and cultures.The 3- and 4-Star charities included in this list have earned their ratings by being financially efficient and transparent in their operations. These nonprofits are larger and national in scope. Smaller and more recently established nonprofits not included in the Star Rating System are assessed via our Encompass Rating System. Organizations with a rating of 75 and above out of 100 have a ‘Give With Confidence’ attribute. Please visit this page for a general list of Encompass charities and enter your preferred keyword(s) in the box within the left sidebar. You can click on the organization’s name to find more details on their performance and mission. From there, you can also access contact information and the option  to donate via the Charity Navigator Giving Basket.",
        day:"",
        update:"",
        member:[],
        activities:[]
    },
    {
        id:"8",
        author:"",
        picture:"https://cn-web-site.s3.amazonaws.com/Hot+Topics+2021/covid-relief.png",
        name:"COVID-19: Relief & Recovery Efforts",
        title:"",
        type:"",
        topic:"",
        content:"More than a year after the World Health Organization classified the coronavirus outbreak as a global health emergency, on May 2, 2021, it was reported that the average for new cases of COVID-19 worldwide was higher than any other time during the pandemic.  Although vaccines have been released in many countries, new cases have skyrocketed making scenes in countries like India, Brazil, Turkey, and Iran, catastrophic. At issue are economic constraints, inadequate supply of testing kits and vaccines, lack of infrastructure and insufficient, qualified medical personnel to administer vaccinations, among others.  Adding to the challenge are new, deadlier variants of the virus that are difficult to contain and treat. We encourage donor support of the highly-rated nonprofits presented on this page. These organizations have created funds to support communities in the U.S. and around the world affected by the outbreak.",
        day:"",
        update:"",
        member:[],
        activities:[]
    },
    {
        id:"9",
        author:"",
        picture:"https://d20umu42aunjpx.cloudfront.net/Hot+Topics+2020/voting-rights-header.jpg",
        name:"Voting Rights and Election Laws",
        title:"",
        type:"",
        topic:"",
        content:"The right to vote has been one of the most important and revered rights within the United States Constitution. The ability to exercise this right has sometimes been contentious and hard-fought along gender and racial lines. The issues of election laws, voting rights, voter registration and suppression, and reform, have been at the forefront of discussions, debates, and protests. Many individuals and organizations work year-round to ensure that as many Americans as possible have equal access to the polls.Charity Navigator encourages citizens to do their research, become informed about how to register and their registration eligibility, have clarity about voting procedures, and utilize information provided by their state's board of elections.For donors looking to ensure that voters have access to free, fair, and secure voting, Charity Navigator’s expert analysts have identified the nonprofits featured on this page. These organizations have programs dedicated to  voter education, registration, election law reform and protection, as well as election monitoring and accountability.  Charity Navigator will continuously update this resource as additional nonprofits are identified and vetted by our analyst team.To nonprofits, if you are a 3- or 4-Star rated charity directly involved in the causes noted above; please complete this survey for your organization to be reviewed for this list.",
        day:"",
        update:"",
        member:[],
        activities:[]
    },
    {
        id:"10",
        author:"",
        picture:"./asset/img/imgProject/topic10.jpg",
        name:"Environmental Nonprofits",
        title:"",
        type:"",
        topic:"",
        content:"The urgency behind many current environmental issues – like climate change, deforestation, and pollution to name a few – has inspired action worldwide. Beyond taking individual actions (like reducing your carbon footprint, for example), an effective way to work towards a more sustainable future is to support nonprofits that are actively seeking to solve some of the world’s most pressing environmental problems.The following charities focus their efforts on a variety of environmental issues, from protecting earth’s resources to advocating for stronger policies and direct action. As highly rated 3- and 4-star charities, they meet or exceed industry standards and perform as well as, or better than, most organizations in their cause areas. Consider making a donation to one of these organizations today!",
        day:"",
        update:"",
        member:[],
        activities:[]
    },
]

export default projects